### ISSUE TITLE
Migration dependency breaks compatibility with django-cms < 2.4

### ISSUE THREAD

**Issue by brente** [divio/cmsplugin-filer#130]
This commit 
https://github.com/stefanfoulis/cmsplugin-filer/commit/d6b9873b926e93da7dca590984fdea2880b5c381#diff-6ea1e68b5bdab76d211051ad70f6cea4
breaks compatibility with django-cms < 2.4, because migration `0039_auto__del_field_page_moderator_state` was only added in django-cms 2.4.0.

The last migration for django-cms 2.2 is 0035, and 2.3.2 adds 0036.

Migrations 0037-0039 clean up after the removal of the legacy moderator.

**Comment by czpython** [comment]
Hi there,

CMS 2.4 is no longer officially supported.
