### ISSUE TITLE
cmsplugin_filer_link lost reference inside ckeditor

### ISSUE THREAD

**Issue by rocchidavide** [divio/cmsplugin-filer#160]
Inside a generic text cms plugin:
1) add inside ckeditor a cmsplugin_filer_link
2) save
3) edit again the text

Le reference to che cmsplugin_filer_link is lost: the is only a 
```html
<p>&nbsp;</p>
```

**Comment by mkoistinen** [comment]
Unable to reproduce. Please re-open if still relevant.
