### ISSUE TITLE
cmsplugin_filer_link renaming multiword link duplicates plugin

### ISSUE THREAD

**Issue by darbula** [divio/cmsplugin-filer#179]
To reproduce

1. In text editor add text `multi link` select and add *CMSPlugin > Link* add some url and save

2. Double click on `multi link` edit name so it becomes `multi word link` and save

Now there is seemingly one link named `multimulti word link​link` but code reveals that there are two link plugins with same reference:

```
<p>
<img alt="Link" id="plugin_obj_60" src="/static/cms/images/plugins/link.png" title="Link - multi link" />
<img alt="Link" id="plugin_obj_60" src="/static/cms/images/plugins/link.png" title="Link - multi word link" />
link
</p>
```

Needless to say for unsuspecting user it is unsolvable problem.

This is tested on clean django cms project with following versions of relevant applications:

```
Django==1.6.10
cmsplugin-filer==0.10.1
django-cms==3.0.12
django-filer==0.9.9
djangocms-text-ckeditor==2.4.3
```

**Comment by mkoistinen** [comment]
This is a known "issue" with `cmsplugin-text-ckeditor` and it should be addressed there.

I'm closing this ticket.

**Comment by darbula** [comment]
Should this issue be copied there then? Is it issue or "issue" :)

**Comment by mkoistinen** [comment]
Yea, I did copy it over (we must've crossed wires).

**Comment by darbula** [comment]
Definitely, race condition.
