### ISSUE TITLE
browse to add image error 

### ISSUE THREAD

**Issue by Alwerdani** [divio/cmsplugin-filer#197]
Hello,
there is a problem when i going to browose  to add image 
```
MultipleObjectsReturned at /en/admin/filer/folder/last/
get() returned more than one Clipboard -- it returned 2!
```
i don't know what happen !

**Comment by marcosguedes** [comment]
It seems it's a problem with Filer itself. The same happened to me with a FilerImageField.

I solved it by deleting the database tables and starting again. Check if there are no pending migrations. If not, clean (migrate zero) filer tables.
I'm Using:
Django 1.8.5
Django CMS 3.2.0
Filer 1.0.2

**Comment by stefanfoulis** [comment]
In newer versions of django-filer the clipboard has been removed/hidden. closing.
