### ISSUE TITLE
"Add Picture" Plugin missing "class" / "width" / "height"

### ISSUE THREAD

**Issue by FinalAngel** [divio/cmsplugin-filer#205]
https://github.com/divio/django-cms/issues/4774

Reported by @bartmika

Hello,

I am a novice so forgive me if I make a mistake. But I am lookin at adding a "Picture" placeholder.

![screen shot 2015-11-26 at 10 19 03 am](https://cloud.githubusercontent.com/assets/5767602/11426075/740cef92-9427-11e5-9081-6908bd5c1412.png)

My problem is the picture image needs to look like this:
  ```
  <img src="img/ps.png" alt="#" class="img-responsive center-block" width="200" height="200">
  ```

So I am wondering how can I input the **class** / **width** / **height** html attributes? Maybe adding a **id** and **onclick** in the futue might help too. If the picture plugin doesn't support this, I think I'd like to open up a issue requesting we can add more html attributes. If it's a mistake on my part, my appoligies in advance!

**Comment by stefanfoulis** [comment]
I think it would be ok to add a ``classes`` field for additional css classes. ``width`` and ``height`` should not be set manually. If you want them on the ``img`` tag, you could override the template. ``id`` seems like it is too likely to create invalid html (duplicate id on same page).

If you happen to be using Bootstrap3, we also have a bootstrap3 specific plugin which already has the fields you proposed: https://github.com/aldryn/aldryn-bootstrap3/blob/eb63de483217839725d991e9b820a1ea5c919ff7/aldryn_bootstrap3/models.py#L217-L294

**Comment by stefanfoulis** [comment]
@bartmika

**Comment by bartmika** [comment]
Thanks @stefanfoulis! I will use that plugin from the **aldryn-bootstrap3** library.

**Comment by stefanfoulis** [comment]
@bartmika great :-) . I'll close this issue for now.

**Comment by k-funk** [comment]
+1 for this. I don't want `img-responsive center-block` on all my images, and it seems like overkill to override the plugin just to add that class to an `img` tag.  I also use some generic styles that are not part of bootstrap, so aldryn-bootstrap3 doesn't quite solve my problem.

Referencing this [old issue](https://github.com/divio/django-filer/issues/339) to go along with this.

**Comment by stefanfoulis** [comment]
@k-funk There is now also divio/djangocms-picture which uses filer as well and is slated to eventually replace the image plugin from cmsplugin-filer.
That one has a attributes field, where you can add additional attributes to the ``img`` tag: https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/models.py#L107
