### ISSUE TITLE
Django filer image resizing

### ISSUE THREAD

**Issue by maxkeogh** [divio/cmsplugin-filer#214]
Hi,
I'm trying to get images to resize using django cms and filer.
I have cmsplugin-filer 1.0.0, django-filer 1.0.2 and Pillow 3.0.0
On the image properties I select "use automatic scaling" but the image does not resize.
Is there a definitive guide for newbies to get image resizing working using django cms and filer?

Many thanks
Max

**Comment by jgoettsch** [comment]
From a quick look at the code it appears you need to have a "width" variable in context in the placeholder. [The Django-CMS template tag docs](https://django-cms.readthedocs.org/en/develop/reference/templatetags.html#placeholder) explain how to do that.

Another way to do it is to use CSS. A rule like this could do it:

```css
p .filer_image {
    height: auto;
    max-width: 100%;
    width: 100%;
}
```

All images from cmsplugin-filer get the filer_image class added to them.
