### ISSUE TITLE
Filer Folder privileges not working

### ISSUE THREAD

**Issue by tomiit123** [divio/cmsplugin-filer#226]
Hi guys. I think I found a bug.
I created new user with check box checked "Active" and "Staff" and add to him all privileges in section add user privileges. Now when I log in as user, open Filer Folder in DjangoCMS administration and I dont see "Add Folder" button and I cant add folder or upload anything. There is only buttons to delete, copy etc. but not blue button Add new Folder.
This is working just and only when I add to user Super User rights with check box in DjangoCMS User Settings. I think this is same in Filer File.

**Comment by stefanfoulis** [comment]
make sure you have ``FILER_ENABLE_PERMISSIONS=True`` set. And then head over to /admin/filer/folderpermission/ and add a permission for "all items" with can edit / can read / can add children for the user/group you want to give access.

**Comment by tomiit123** [comment]
Thank you Stefan. I didnt know that. Right now it is working but only in folder not in root. But I think it alright that way.
