### ISSUE TITLE
Where's version 1.1?

### ISSUE THREAD

**Issue by philippze** [divio/cmsplugin-filer#237]
The README promises an "Upgrade to version 1.1". Can I find this version anywhere already?

**Comment by stefanfoulis** [comment]
Thanks for pointing that out. Since ``django-filer 1.2`` has been released now, we could release ``cmsplugin-filer 1.1``.
@yakky is everything ready for a release regarding the thumbnail options thingy?

**Comment by yakky** [comment]
@stefanfoulis everything is green

**Comment by pawelmarkowski** [comment]
@stefanfoulis @yakky and ... ? :)

**Comment by stefanfoulis** [comment]
@yakky or @mkoistinen : Would be awesome if one of you make the release. 🏆  😄

**Comment by yakky** [comment]
@mkoistinen is working on some new addition for 1.1, I'll let him do the release when done

**Comment by stefanfoulis** [comment]
👍

**Comment by mkoistinen** [comment]
Version 1.1.1 was released on 22-June-2016. Closing.
