### ISSUE TITLE
How to override default.html template?

### ISSUE THREAD

**Issue by iainhouston** [divio/cmsplugin-filer#267]
A request for help from someone new to this.  

I want to override styling such as which slideshow image properties to use in `.../lib/python3.5/site-packages/cmsplugin_filer_folder/templates/cmsplugin_filer_folder/plugins/folder/default.html`. 

... presumably by placing an updated version of this in my app's `templates` directory.

Where - in the code - would I expect to find out the answer to this in future?

**Comment by rspeed** [comment]
I'm not sure what you're asking. This behavior is the same as any other Django application.

**Comment by iainhouston** [comment]
Excuse my confusion. Sorted.
