### ISSUE TITLE
"Can add Folder" permission not working for root folder

### ISSUE THREAD

**Issue by dietmar** [divio/cmsplugin-filer#279]
When I give users the permission `filer | Folder | Can add Folder`, they can add folders, but not in the root folder. Adding all other available permissions also does not help. Only giving the user superuser status allows them to add a new folder in the root folder.

Note that I am not talking about folder permissions (`FILER_ENABLE_PERMISSIONS=True`), but user permissions set in Home -> Authentication and Authorization -> Users.

#226  is somewhat related, but offers no solution to my situation.

I'm using cmsplugin-filer version 1.1.3

**Comment by didierCH** [comment]
Same is true for me.

**Comment by stefanfoulis** [comment]
@dietmar @didierCH thanks for reporting. This is actually an issue in divio/django-filer. There already is a (pretty old) Issue about it here: https://github.com/divio/django-filer/issues/879
Please add a " 👍 " to that issue to get it bumped.

**Comment by dietmar** [comment]
Thanks @stefanfoulis. I'll close this one then.
