### ISSUE TITLE
running out of memory on larger uploads (nginx+gunicorn)

### ISSUE THREAD

**Issue by HG00** [divio/cmsplugin-filer#93]
Hi

(sorry for the non-specific details)

I'm seeing MemoryErrors when uploading large files. Nginx creates a temp file just fine, but as soon as its done uploading, I can see python's memory usage increase a lot - usually ending with a MemoryError. For some files, I can see the spike in memory while the file is in the "clipboard". As soon as its moved to a folder, the memory is cleared.

Is there a way to force the use of temp files instead of memory for file uploads, or even bypass the clipboard?

Thanks,

**Comment by stefanfoulis** [comment]
closing for now. If this still is an issue, please re-open on the django-filer issue tracker.
